---
title: "Model 3: MSE"
author: "Sophia Kleist Karlson"
date: "22 nov 2020"
output: html_document
---

Model 3: Error between images


```{r}
# set working directory
setwd("~/Social Transmission Study/Analysis of drawings/")

# load necessary packages through pacman
pacman::p_load(tidyverse, brms, ggplot2, stringr, dplyr, bayesplot)

# RStudio version
RStudio.Version()

# read data and delete the first unnecessary columns
data_MSE <- read_csv("data/csv_files/all_data_w_MSE.csv") #we use all_data_w_MSE.csv
data_MSE$X1 <- NULL
```


Preparing the data and checking stuff
```{r}
# Checking classes

# Generation and MSE should be numeric
class(data_MSE$Generation)
class(data_MSE$MSE)

# Subject and Drawing ID should be character
class(data_MSE$Subject)
class(data_MSE$Drawing_ID)

# Chain, condition and Source_image should be factors
class(data_MSE$Chain)
class(data_MSE$Condition)
class(data_MSE$Source_image)

data_MSE$Chain <- as.factor(data_MSE$Chain)
data_MSE$Condition <- as.factor(data_MSE$Condition)
data_MSE$Source_image <- as.factor(data_MSE$Source_image)


# Chose the variables needed for the model
df_MSE <- data_MSE %>% select(Subject, Chain, Generation, Condition, Source_image, MSE)

# Z-score outcome variable to make it easier to deal with and interpret
df_MSE$MSE <- scale(df_MSE$MSE)
```


Look at each conditions
```{r}
# check mean MSE of each of the conditions
Cond1_MSE <- df_MSE %>% subset(Condition == 1) %>% subset(Generation == 0) %>% select(MSE) 
Cond1_MSE$MSE <- as.numeric(Cond1_MSE$MSE)
mean(Cond1_MSE$MSE) # at gen 0: 0.6771817. Overall: 0.8745232

Cond2_MSE <- df_MSE %>% subset(Condition == 2) %>% subset(Generation == 0) %>% select(MSE) 
Cond2_MSE$MSE <- as.numeric(Cond2_MSE$MSE)
mean(Cond2_MSE$MSE) # at gen 0: 0.3701661. Overall: -0.3798595

Cond3_MSE <- df_MSE %>% subset(Condition == 3) %>% subset(Generation == 0) %>% select(MSE)
Cond3_MSE$MSE <- as.numeric(Cond3_MSE$MSE)
mean(Cond3_MSE$MSE)# at gen 0: 0.5331424. Overall: -0.2153379

Cond4_MSE <- df_MSE %>% subset(Condition == 4) %>% subset(Generation == 0) %>% select(MSE)
Cond4_MSE$MSE <- as.numeric(Cond4_MSE$MSE)
mean(Cond4_MSE$MSE)# at gen 0: 0.4362941. Overall: -0.2793258
```


Modeling
```{r}
# Set seed so that the analysis can be re-run and give the same results
set.seed(555)

# Define the model
MSE_mod <- bf(MSE ~ 0 + Condition + mo(Generation) + Condition:mo(Generation) + 
                       (1 + Condition | gr(Subject, by = Chain)) +
                       (1 + Condition + mo(Generation) + Condition:mo(Generation) | Source_image))

# Figure out what priors we'll need
get_prior(MSE_mod, family = gaussian, df_MSE)

# Checking range, mean and standard deviation of complexity, to determine which family to choose and to use for beta-prior
range(df_MSE$MSE)
mean(df_MSE$MSE)
sd(df_MSE$MSE)


# For choosing the sd prior
df_part <- df_MSE %>% group_by(Subject) %>% summarize(mean_MSE = mean(MSE)) #find mean complexity for each participant
sd(df_part$mean_MSE)/2 #get the standard deviation of the mean complexity for each participant. Divide this in two

# do the same, but grouping by source image
df_source <- df_MSE %>% group_by(Source_image) %>% summarize(MSE_mean = mean(MSE)) # find mean conventionality for each source image
sd(df_source$MSE_mean)/2 # scaled = 0.12, half = 0.06



prior_MSE_mod <- c(
  prior(normal(0, 1),           class = b), #mean and sd of MSE #4.38, 2.81
  prior(normal(1, 0.5),         class = sigma), #mean: sd of MSE sigma: half of the sd of MSE #2.81, 1.40
  prior(normal(0, 0.22),        class = sd), #mean: 0 (I expect that they might not vary at all). sd for the mean MSE for each participant = 2780.45. sigma should go from 0 (the mean of the prior) to around that -> sigma: 1390.23.
  prior(lkj(1),                 class = cor), # I choose lkj prior of 1
  
  # simo priors for the monotonic generation variable: mean is 1 for a uniform prior, sigma is K-1, where K is the number of levels in the monotonic variable (we have 7 generations)
  prior(dirichlet(rep(1, 6)),   class = simo, coef = moGeneration:Condition21),                 
  prior(dirichlet(rep(1, 6)),   class = simo, coef = moGeneration:Condition31),             
  prior(dirichlet(rep(1, 6)),   class = simo, coef = moGeneration:Condition41),            
  prior(dirichlet(rep(1, 6)),   class = simo, coef = moGeneration1)
  #prior(normal(4.38, 2.81),     class = Intercept), #mean and sd of MSE
)


# Running the model to check priors
MSE_mod0 <- brm(
  formula = MSE_mod, 
  prior = prior_MSE_mod,
  data = df_MSE,
  chains = 2,
  cores = 2,
  sample_prior = "only"
)


# Prior predictive check
pp_check(MSE_mod0, nsamples = 100) # 


# The actual model:
MSE_mod1 <- brm(
  formula = MSE_mod, 
  prior = prior_MSE_mod,
  data = df_MSE,
  chains = 2,
  cores = 2,
  sample_prior = T,
  iter = 4000,
  control = list(adapt_delta=0.99, max_treedepth=20)
)

# Posterior predictive check
pp_check(MSE_mod1, nsamples = 100)


# Model summary
summary(MSE_mod1) # Warnings? Suspicious Rhat activity? Bad priors?

# Plot the model to get trace plots
plot(MSE_mod1)

# Rank trace plots
mcmc_rank_overlay(MSE_mod1, 
                  pars = c("b_Condition1", "b_Condition2", "b_Condition3", "b_Condition4")) + 
  theme_classic()

mcmc_rank_overlay(MSE_mod1, 
                  pars = c("bsp_moGeneration", "bsp_moGeneration:Condition2", "bsp_moGeneration:Condition3", "bsp_moGeneration:Condition4")) + 
  theme_classic()

mcmc_rank_overlay(MSE_mod1, 
                  pars = c("sigma")) + 
  theme_classic()


# After trying different hypotheses, these turned out to be the ones with highest evidence ratio

# main effects of conditions
hypothesis(MSE_mod1,"(Condition1*7 + 0.04*21)/7 > 0")
hypothesis(MSE_mod1,"(Condition2*7 - 0.24*21)/7 < 0")
hypothesis(MSE_mod1,"(Condition3*7 - 0.24*21)/7 < 0")
hypothesis(MSE_mod1,"(Condition4*7 - 0.20*21)/7 < 0")

# these two could have replaced the two top ones, but they gave sligtly smaller estimated error, so I chose the other option as seen above
#hypothesis(MSE_mod1,"(0.74*7 + moGeneration*21)/7 > 0", class="bsp")
#hypothesis(MSE_mod1,"(0.34*7 + moGeneration:Condition2*21)/7 < 0", class="bsp")

# relations between the conditions
hypothesis(MSE_mod1,"(Condition1*7 + 0.04*21)/7 > (Condition2*7 - 0.24*21)/7") 
hypothesis(MSE_mod1,"(Condition1*7 + 0.04*21)/7 > (Condition3*7 - 0.24*21)/7")
hypothesis(MSE_mod1,"(Condition1*7 + 0.04*21)/7 > (Condition4*7 - 0.20*21)/7")

hypothesis(MSE_mod1,"(Condition2*7 - 0.24*21)/7 < (Condition3*7 - 0.24*21)/7")
hypothesis(MSE_mod1,"(Condition3*7 - 0.24*21)/7 = (Condition4*7 - 0.20*21)/7")
hypothesis(MSE_mod1,"(Condition2*7 - 0.24*21)/7 = (Condition4*7 - 0.20*21)/7")


# overall effect of generation
hypothesis(MSE_mod1,"((moGeneration + moGeneration:Condition2 + moGeneration:Condition3 + moGeneration:Condition4)/4) < 0", class = "bsp")

# effects of the interactions between generation and conditions
hypothesis(MSE_mod1,"moGeneration > 0", class = "bsp")
hypothesis(MSE_mod1,"moGeneration:Condition2 < 0", class = "bsp") 
hypothesis(MSE_mod1,"moGeneration:Condition3 < 0", class = "bsp") 
hypothesis(MSE_mod1,"moGeneration:Condition4 < 0", class = "bsp")


# plot the best hypotheses
plot(hypothesis(MSE_mod1,"(Condition1*7 + 0.04*21)/7 > 0"))
plot(hypothesis(MSE_mod1,"(Condition2*7 - 0.24*21)/7 < 0"))
plot(hypothesis(MSE_mod1,"(Condition3*7 - 0.24*21)/7 < 0"))
plot(hypothesis(MSE_mod1,"(Condition4*7 - 0.20*21)/7 < 0"))

# these two could have replaced the two top ones, but they gave sligtly smaller estimated error, so I chose the other option as seen above
#hypothesis(MSE_mod1,"(0.74*7 + moGeneration*21)/7 > 0", class="bsp")
#hypothesis(MSE_mod1,"(0.34*7 + moGeneration:Condition2*21)/7 < 0", class="bsp")

# relations between the conditions
plot(hypothesis(MSE_mod1,"(Condition1*7 + 0.04*21)/7 > (Condition2*7 - 0.24*21)/7"))
plot(hypothesis(MSE_mod1,"(Condition1*7 + 0.04*21)/7 > (Condition3*7 - 0.24*21)/7"))
plot(hypothesis(MSE_mod1,"(Condition1*7 + 0.04*21)/7 > (Condition4*7 - 0.20*21)/7"))

plot(hypothesis(MSE_mod1,"(Condition2*7 - 0.24*21)/7 < (Condition3*7 - 0.24*21)/7"))
plot(hypothesis(MSE_mod1,"(Condition3*7 - 0.24*21)/7 = (Condition4*7 - 0.20*21)/7"))
plot(hypothesis(MSE_mod1,"(Condition2*7 - 0.24*21)/7 = (Condition4*7 - 0.20*21)/7"))


# overall effect of generation
plot(hypothesis(MSE_mod1,"((moGeneration + moGeneration:Condition2 + moGeneration:Condition3 + moGeneration:Condition4)/4) < 0", class = "bsp"))

# effects of the interactions between generation and conditions
plot(hypothesis(MSE_mod1,"moGeneration > 0", class = "bsp"))
plot(hypothesis(MSE_mod1,"moGeneration:Condition2 < 0", class = "bsp")) 
plot(hypothesis(MSE_mod1,"moGeneration:Condition3 < 0", class = "bsp")) 
plot(hypothesis(MSE_mod1,"moGeneration:Condition4 < 0", class = "bsp"))


# Plot conditional effects
conditional_effects(MSE_mod1)

conditional_effects(MSE_mod1, effects = "Generation", conditions = make_conditions(MSE_mod1, vars = "Condition"))

head(parnames(MSE_mod1), 10)
```



Tests
1 - only two conditions
```{r}
df_MSE_test <- df_MSE

df_MSE_test$Condition <- as.numeric(df_MSE_test$Condition)

df_MSE_test <- df_MSE_test %>% subset(Condition <3)
df_MSE_test$Condition <- as.factor(df_MSE_test$Condition)

# Set seed so that the analysis can be re-run and give the same results
set.seed(555)

# Define the model
MSE_mod_test <- bf(MSE ~ 0 + mo(Generation) + Condition + mo(Generation):Condition + 
                       (1 + Condition | gr(Subject, by = Chain)) +
                       (1 + mo(Generation) + Condition + mo(Generation):Condition | Source_image))


prior_MSE_mod_test <- c(
  prior(normal(0, 1),           class = b), #mean and sd of MSE #4.38, 2.81
  prior(normal(1, 0.5),         class = sigma), #mean: sd of MSE sigma: half of the sd of MSE #2.81, 1.40
  prior(normal(0, 0.22),        class = sd), #mean: 0 (I expect that they might not vary at all). sd for the mean MSE for each participant = 2780.45. sigma should go from 0 (the mean of the prior) to around that -> sigma: 1390.23.
  prior(lkj(1),                 class = cor), # I choose lkj prior of 1
  
  # simo priors for the monotonic generation variable: mean is 1 for a uniform prior, sigma is K-1, where K is the number of levels in the monotonic variable (we have 7 generations)
  prior(dirichlet(rep(1, 6)),   class = simo, coef = moGeneration:Condition21),                 
  #prior(dirichlet(rep(1, 6)),   class = simo, coef = moGeneration:Condition31),             
  #prior(dirichlet(rep(1, 6)),   class = simo, coef = moGeneration:Condition41),            
  prior(dirichlet(rep(1, 6)),   class = simo, coef = moGeneration1)
  #prior(normal(4.38, 2.81),     class = Intercept), #mean and sd of MSE
)


# The actual model:
MSE_mod1_test <- brm(
  formula = MSE_mod_test, 
  prior = prior_MSE_mod_test,
  data = df_MSE_test,
  chains = 2,
  cores = 2,
  sample_prior = T,
  iter = 2000,
  control = list(adapt_delta=0.99, max_treedepth=20)
)

# Model summary
summary(MSE_mod1_test) # Warnings? Suspicious Rhat activity? Bad priors?

# Plot conditional effects
conditional_effects(MSE_mod1_test)

head(parnames(MSE_mod1_test), 10)



# After trying different hypotheses, these turned out to be the ones with highest evidence ratio

# to get the main effect of condition 1 we have to use the slope of generation for condition 1, because we only have the intercept - but as we can't combine the effects of the condition and generation variables because they have differnet classes, then I just take the estimates from generation, even though this doesn't encompass the varition... you can see that these two give slightly  different results: 
hypothesis(MSE_mod1_test,"(Condition1*7 + 0.05*21)/7 > 0") # est:.88, err=0.1
hypothesis(MSE_mod1_test,"(0.73*7 + moGeneration*21)/7 > 0", class="bsp")# est:.87, err=0.08

hypothesis(MSE_mod1_test,"(Condition2*7 + -0.25*21)/7 < 0") # est:.-0.39, err=0.13
hypothesis(MSE_mod1_test,"(0.36*7 + moGeneration:Condition2*21)/7 < 0", class="bsp")# est:.-.38, err=0.08

hypothesis(MSE_mod1,"(Condition1 + Condition2) < 0")
hypothesis(MSE_mod1,"(Condition1 + Condition3) < 0")
hypothesis(MSE_mod1,"(Condition1 + Condition4) < 0")

hypothesis(MSE_mod1,"Condition1 > (Condition1 + Condition2)") 
hypothesis(MSE_mod1,"Condition1 > (Condition1 + Condition3)")
hypothesis(MSE_mod1,"Condition1 > (Condition1 + Condition4)")

hypothesis(MSE_mod1,"(Condition1 + Condition2) = (Condition1 + Condition3)")
hypothesis(MSE_mod1,"(Condition1 + Condition3) = (Condition1 + Condition4)")
hypothesis(MSE_mod1,"(Condition1 + Condition2) = (Condition1 + Condition4)")

# overall effect of generation
hypothesis(MSE_mod1,"((moGeneration + (moGeneration + moGeneration:Condition2) + (moGeneration + moGeneration:Condition3) + (moGeneration + moGeneration:Condition4))/4 > 0", class = "bsp")

# effects of the interactions between generation and conditions
hypothesis(MSE_mod1,"moGeneration < 0", class = "bsp")
hypothesis(MSE_mod1,"(moGeneration + moGeneration:Condition2) < 0", class = "bsp") 
hypothesis(MSE_mod1,"(moGeneration + moGeneration:Condition3) < 0", class = "bsp") 
hypothesis(MSE_mod1,"(moGeneration + moGeneration:Condition4) < 0", class = "bsp")
```


2 - only two conditions and only modeling condition
```{r}
df_MSE_test2 <- df_MSE_test

# Set seed so that the analysis can be re-run and give the same results
set.seed(555)

# Define the model
MSE_mod_test2 <- bf(MSE ~ 0 + Condition + 
                       (1 + Condition | gr(Subject, by = Chain)) +
                       (1 + Condition | Source_image))


prior_MSE_mod_test2 <- c(
  prior(normal(0, 1),           class = b), #mean and sd of MSE #4.38, 2.81
  prior(normal(1, 0.5),         class = sigma), #mean: sd of MSE sigma: half of the sd of MSE #2.81, 1.40
  prior(normal(0, 0.22),        class = sd), #mean: 0 (I expect that they might not vary at all). sd for the mean MSE for each participant = 2780.45. sigma should go from 0 (the mean of the prior) to around that -> sigma: 1390.23.
  prior(lkj(1),                 class = cor) # I choose lkj prior of 1
  
  # simo priors for the monotonic generation variable: mean is 1 for a uniform prior, sigma is K-1, where K is the number of levels in the monotonic variable (we have 7 generations)
  #prior(dirichlet(rep(1, 6)),   class = simo, coef = moGeneration:Condition21),                 
  #prior(dirichlet(rep(1, 6)),   class = simo, coef = moGeneration:Condition31),             
  #prior(dirichlet(rep(1, 6)),   class = simo, coef = moGeneration:Condition41),            
  #prior(dirichlet(rep(1, 6)),   class = simo, coef = moGeneration1)
  #prior(normal(4.38, 2.81),     class = Intercept), #mean and sd of MSE
)


# The actual model:
MSE_mod1_test2 <- brm(
  formula = MSE_mod_test2, 
  prior = prior_MSE_mod_test2,
  data = df_MSE_test2,
  chains = 2,
  cores = 2,
  sample_prior = T,
  iter = 2000,
  control = list(adapt_delta=0.99, max_treedepth=20)
)

# Model summary
summary(MSE_mod1_test2) # Warnings? Suspicious Rhat activity? Bad priors?

# Plot conditional effects
conditional_effects(MSE_mod1_test)

conditional_effects(MSE_mod1_test, effects = "Generation", conditions = make_conditions(MSE_mod1, vars = "Condition"))

head(parnames(MSE_mod1_test), 10)

# After trying different hypotheses, these turned out to be the ones with highest evidence ratio
hypothesis(MSE_mod1,"Condition1 > 0")
hypothesis(MSE_mod1,"(Condition1 + Condition2) < 0")
hypothesis(MSE_mod1,"(Condition1 + Condition3) < 0")
hypothesis(MSE_mod1,"(Condition1 + Condition4) < 0")

hypothesis(MSE_mod1,"Condition1 > (Condition1 + Condition2)") 
hypothesis(MSE_mod1,"Condition1 > (Condition1 + Condition3)")
hypothesis(MSE_mod1,"Condition1 > (Condition1 + Condition4)")

hypothesis(MSE_mod1,"(Condition1 + Condition2) = (Condition1 + Condition3)")
hypothesis(MSE_mod1,"(Condition1 + Condition3) = (Condition1 + Condition4)")
hypothesis(MSE_mod1,"(Condition1 + Condition2) = (Condition1 + Condition4)")

# overall effect of generation
hypothesis(MSE_mod1,"((moGeneration + (moGeneration + moGeneration:Condition2) + (moGeneration + moGeneration:Condition3) + (moGeneration + moGeneration:Condition4))/4 > 0", class = "bsp")

# effects of the interactions between generation and conditions
hypothesis(MSE_mod1,"moGeneration < 0", class = "bsp")
hypothesis(MSE_mod1,"(moGeneration + moGeneration:Condition2) < 0", class = "bsp") 
hypothesis(MSE_mod1,"(moGeneration + moGeneration:Condition3) < 0", class = "bsp") 
hypothesis(MSE_mod1,"(moGeneration + moGeneration:Condition4) < 0", class = "bsp")


# plot the best hypotheses
plot(hypothesis(MSE_mod1,"Condition1 = 0"))
plot(hypothesis(MSE_mod1,"(Condition1 + Condition2) < 0"))
plot(hypothesis(MSE_mod1,"(Condition1 + Condition3) < 0"))
plot(hypothesis(MSE_mod1,"(Condition1 + Condition4) < 0"))

plot(hypothesis(MSE_mod1,"Condition1 > (Condition1 + Condition2)")) 
plot(hypothesis(MSE_mod1,"Condition1 > (Condition1 + Condition3)"))
plot(hypothesis(MSE_mod1,"Condition1 > (Condition1 + Condition4)"))

plot(hypothesis(MSE_mod1,"(Condition1 + Condition2) = (Condition1 + Condition3)"))
plot(hypothesis(MSE_mod1,"(Condition1 + Condition3) = (Condition1 + Condition4)"))
plot(hypothesis(MSE_mod1,"(Condition1 + Condition2) = (Condition1 + Condition4)"))

plot(hypothesis(MSE_mod1,"((moGeneration + (moGeneration + moGeneration:Condition2) + (moGeneration + moGeneration:Condition3) + (moGeneration + moGeneration:Condition4))/4 > 0", class = "bsp"))
plot(hypothesis(MSE_mod1,"moGeneration < 0", class = "bsp"))
plot(hypothesis(MSE_mod1,"(moGeneration + moGeneration:Condition2) < 0", class = "bsp"))
plot(hypothesis(MSE_mod1,"(moGeneration + moGeneration:Condition3) < 0", class = "bsp")) 
plot(hypothesis(MSE_mod1,"(moGeneration + moGeneration:Condition4) < 0", class = "bsp"))
```

