---
title: "Model 1: Complexity"
author: "Sophia Kleist Karlson"
date: "13 nov 2020"
output: html_document
---

Model 1: Complexity


```{r}
# set working directory
setwd("~/Social Transmission Study/Analysis of drawings/")

# load necessary packages through pacman
pacman::p_load(tidyverse, brms, ggplot2, stringr, dplyr, bayesplot)

# RStudio version
RStudio.Version()

# read data and delete the first unnecessary columns
data_comp <- read_csv("data/csv_files/all_data_w_source.csv") # we use all_data_w_all_conv_source.csv
data_comp$X1 <- NULL
```


Preparing the data and checking stuff
```{r}
# Checking classes

# Generation, complexity and confidence should be numeric
class(data_comp$Generation)
class(data_comp$Confidence)
class(data_comp$Complexity)

# Subject and Drawing ID should be character
class(data_comp$Subject)
class(data_comp$Drawing_ID)

# Chain, condition and Source_image should be factors
class(data_comp$Chain)
class(data_comp$Condition)
class(data_comp$Source_image)

data_comp$Chain <- as.factor(data_comp$Chain)
data_comp$Condition <- as.factor(data_comp$Condition)
data_comp$Source_image <- as.factor(data_comp$Source_image)


# Chose the variables needed for the model
df_complexity <- data_comp %>% select(Subject, Chain, Generation, Condition, Source_image, Complexity)#, Drawing_ID

# Z-score outcome variable to make it easier to deal with and interpret
df_complexity$Complexity <- scale(df_complexity$Complexity)


# check mean complexity of each of the conditions
class(df_complexity$Complexity)
Cond1_comp <- df_complexity %>% subset(Condition == 1) %>% subset(Generation == 0) %>% select(Complexity) 
Cond1_comp$Complexity <- as.numeric(Cond1_comp$Complexity)
mean(Cond1_comp$Complexity) # at gen 0: 0.759147. Overall: 0.8644237

Cond2_comp <- df_complexity %>% subset(Condition == 2) %>% subset(Generation == 0) %>% select(Complexity) 
Cond2_comp$Complexity <- as.numeric(Cond2_comp$Complexity)
mean(Cond2_comp$Complexity) # at gen 0: 0.7259283. Overall: -0.3349807

Cond3_comp <- df_complexity %>% subset(Condition == 3) %>% subset(Generation == 0) %>% select(Complexity)
Cond3_comp$Complexity <- as.numeric(Cond3_comp$Complexity)
mean(Cond3_comp$Complexity) # at gen 0: 0.7027229. Overall: -0.2500194

Cond4_comp <- df_complexity %>% subset(Condition == 4) %>% subset(Generation == 0) %>% select(Complexity)
Cond4_comp$Complexity <- as.numeric(Cond4_comp$Complexity)
mean(Cond4_comp$Complexity) # at gen 0: 0.7707145. Overall: -0.2794236
```


Modeling
```{r}
# Set seed so that the analysis can be re-run and give the same results
set.seed(555)

# Define the model
complexity_mod <- bf(Complexity ~ 0 + Condition + mo(Generation) + Condition:mo(Generation) + 
                       (1 + Condition | gr(Subject, by = Chain)) +
                       (1 + Condition + mo(Generation) + Condition:mo(Generation) | Source_image))


# Figure out what priors we'll need
get_prior(complexity_mod, family = gaussian, df_complexity)

# Checking range, mean and standard deviation of complexity, to determine which family to choose and to use for beta-prior
range(df_complexity$Complexity)
mean(df_complexity$Complexity)
sd(df_complexity$Complexity)


# For choosing the sd prior
df_part <- df_complexity %>% group_by(Subject) %>% summarize(compl_mean = mean(Complexity)) #find mean complexity for each participant
sd(df_part$compl_mean) #get the standard deviation of the mean complexity for each participant = 3159.295. Divide this in two = 1579.648. Scaled: 0.49, half = 0.25

# do the same, but grouping by source image
df_source <- df_complexity %>% group_by(Source_image) %>% summarize(mean_comp = mean(Complexity)) # find mean conventionality for each source image
sd(df_source$mean_comp) # scaled = 0.25, half = 0.12


prior_complexity_mod <- c(
  prior(normal(0, 1),           class = b), #mean and sd of complexity: 24641.25, 6401.52. z-scored: 0, 1
  prior(normal(1, 0.5),         class = sigma), #mean: sd of complexity sigma: half of the sd of complexity: 6401.52, 3200.76. z-scored: 1, 0.5
  prior(normal(0, 0.25),        class = sd), #mean: 0 (I expect that they might not vary at all). sd for the mean complexity for each participant = 2780.45. sigma should go from 0 (the mean of the prior) to around that -> sigma: 1579.648. Z-scored: 0, 0.25.
  prior(lkj(1),                 class = cor),# I choose lkj prior of 1
  
  # simo priors for the monotonic generation variable: mean is 1 for a uniform prior, sigma is K-1, where K is the number of levels in the monotonic variable (we have 8 generations)
  prior(dirichlet(rep(1, 7)),   class = simo, coef = moGeneration:Condition21),                 
  prior(dirichlet(rep(1, 7)),   class = simo, coef = moGeneration:Condition31),             
  prior(dirichlet(rep(1, 7)),   class = simo, coef = moGeneration:Condition41),            
  prior(dirichlet(rep(1, 7)),   class = simo, coef = moGeneration1)
)


# Running the model to check priors
complexity_mod0 <- brm(
  formula = complexity_mod, 
  prior = prior_complexity_mod,
  data = df_complexity,
  chains = 2,
  cores = 2,
  sample_prior = "only"
)


# Prior predictive check
pp_check(complexity_mod0, nsamples = 100) 


# The actual model:
complexity_mod1 <- brm(
  formula = complexity_mod, 
  prior = prior_complexity_mod,
  data = df_complexity,
  chains = 2,
  cores = 2,
  sample_prior = T,
  iter = 4000,
  control = list(adapt_delta=0.99, max_treedepth=20)
)

# Posterior predictive check
pp_check(complexity_mod1, nsamples = 100)



# Model summary
summary(complexity_mod1) # Warnings? Suspicious Rhat activity? Bad priors?


# Plot the model to get trace plots
plot(complexity_mod1)


# Rank trace plots
mcmc_rank_overlay(complexity_mod1, 
                  pars = c("b_Condition1", "b_Condition2", "b_Condition3", "b_Condition4")) + 
  theme_classic()

mcmc_rank_overlay(complexity_mod1, 
                  pars = c("bsp_moGeneration", "bsp_moGeneration:Condition2", "bsp_moGeneration:Condition3", "bsp_moGeneration:Condition4")) + 
  theme_classic()

mcmc_rank_overlay(complexity_mod1, 
                  pars = c("sigma")) + 
  theme_classic()


# After trying different hypotheses, these turned out to be the ones with highest evidence ratio

# main effects of conditions 
# 0 actually doesn't mean anything in these four, because it's not a slope, it's just an average effect - and as the variables are z-scored, the mean effect will be closer to 0 for the three memory conditions because they all drag the mean down towards them - so instead of comparing with 0, we should compare with the mean effect of condition at generation 0
hypothesis(complexity_mod1,"(Condition1*8 + 0.01*28)/8 > 0")
hypothesis(complexity_mod1,"(Condition2*8 - 0.25*28)/8 < 0")
hypothesis(complexity_mod1,"(Condition3*8 - 0.22*28)/8 = 0")
hypothesis(complexity_mod1,"(Condition4*8 - 0.21*28)/8 = 0")

# these two could have replaced the two top ones, but they gave sligtly smaller estimated error, so I chose the other option as seen above
#hypothesis(complexity_mod1,"(0.82*8 + moGeneration*28)/8 > 0", class="bsp")
#hypothesis(complexity_mod1,"(0.67*8 + moGeneration:Condition2*28)/8 < 0", class="bsp")
#hypothesis(complexity_mod1,"(0.65*8 + moGeneration:Condition3*28)/8 < 0", class="bsp")
#hypothesis(complexity_mod1,"(0.62*8 + moGeneration:Condition4*28)/8 = 0", class="bsp")

# relations between the conditions
hypothesis(complexity_mod1,"(Condition1*8 + 0.01*28)/8 > (Condition2*8 - 0.25*28)/8") 
hypothesis(complexity_mod1,"(Condition1*8 + 0.01*28)/8 > (Condition3*8 - 0.22*28)/8")
hypothesis(complexity_mod1,"(Condition1*8 + 0.01*28)/8 > (Condition4*8 - 0.21*28)/8")
hypothesis(complexity_mod1,"(Condition2*8 - 0.25*28)/8 = (Condition3*8 - 0.22*28)/8")
hypothesis(complexity_mod1,"(Condition2*8 - 0.25*28)/8 = (Condition4*8 - 0.21*28)/8")
hypothesis(complexity_mod1,"(Condition3*8 - 0.22*28)/8 = (Condition4*8 - 0.21*28)/8")


# overall effect of generation
hypothesis(complexity_mod1,"((moGeneration + moGeneration:Condition2 + moGeneration:Condition3 + moGeneration:Condition4)/4) < 0", class = "bsp")

# effects of the interactions between generation and conditions
hypothesis(complexity_mod1,"moGeneration = 0", class = "bsp")
hypothesis(complexity_mod1,"moGeneration:Condition2 < 0", class = "bsp") 
hypothesis(complexity_mod1,"moGeneration:Condition3 < 0", class = "bsp") 
hypothesis(complexity_mod1,"moGeneration:Condition4 < 0", class = "bsp")

hypothesis(complexity_mod1,"moGeneration > moGeneration:Condition2", class = "bsp")
hypothesis(complexity_mod1,"moGeneration > moGeneration:Condition3", class = "bsp") 
hypothesis(complexity_mod1,"moGeneration > moGeneration:Condition4", class = "bsp") 
hypothesis(complexity_mod1,"moGeneration:Condition2 = moGeneration:Condition3", class = "bsp")
hypothesis(complexity_mod1,"moGeneration:Condition2 = moGeneration:Condition4", class = "bsp")
hypothesis(complexity_mod1,"moGeneration:Condition3 = moGeneration:Condition4", class = "bsp") 


# the ones that we expected but that didn't have the highest ER
hypothesis(complexity_mod1,"(Condition2*8 - 0.25*28)/8 > (Condition3*8 - 0.22*28)/8")
hypothesis(complexity_mod1,"(Condition2*8 - 0.25*28)/8 > (Condition4*8 - 0.21*28)/8")
hypothesis(complexity_mod1,"(Condition3*8 - 0.22*28)/8 > (Condition4*8 - 0.21*28)/8")

hypothesis(complexity_mod1,"moGeneration:Condition2 > moGeneration:Condition3", class = "bsp")
hypothesis(complexity_mod1,"moGeneration:Condition2 > moGeneration:Condition4", class = "bsp")
hypothesis(complexity_mod1,"moGeneration:Condition3 > moGeneration:Condition4", class = "bsp")


# plot the best hypotheses
plot(hypothesis(complexity_mod1,"(Condition1*8 + 0.01*28)/8 > 0"))
plot(hypothesis(complexity_mod1,"(Condition2*8 - 0.25*28)/8 < 0"))
plot(hypothesis(complexity_mod1,"(Condition3*8 - 0.22*28)/8 = 0"))
plot(hypothesis(complexity_mod1,"(Condition4*8 - 0.21*28)/8 = 0"))

plot(hypothesis(complexity_mod1,"(Condition1*8 + 0.01*28)/8 > (Condition2*8 - 0.25*28)/8"))
plot(hypothesis(complexity_mod1,"(Condition1*8 + 0.01*28)/8 > (Condition3*8 - 0.22*28)/8"))
plot(hypothesis(complexity_mod1,"(Condition1*8 + 0.01*28)/8 > (Condition4*8 - 0.21*28)/8"))
plot(hypothesis(complexity_mod1,"(Condition2*8 - 0.25*28)/8 = (Condition3*8 - 0.22*28)/8"))
plot(hypothesis(complexity_mod1,"(Condition3*8 - 0.22*28)/8 = (Condition4*8 - 0.21*28)/8"))
plot(hypothesis(complexity_mod1,"(Condition2*8 - 0.25*28)/8 = (Condition4*8 - 0.21*28)/8"))

plot(hypothesis(complexity_mod1,"((moGeneration + moGeneration:Condition2 + moGeneration:Condition3 + moGeneration:Condition4)/4) < 0", class = "bsp"))

plot(hypothesis(complexity_mod1,"moGeneration > 0", class = "bsp"))
plot(hypothesis(complexity_mod1,"moGeneration:Condition2 < 0", class = "bsp")) 
plot(hypothesis(complexity_mod1,"moGeneration:Condition3 < 0", class = "bsp")) 
plot(hypothesis(complexity_mod1,"moGeneration:Condition4 < 0", class = "bsp"))

plot(hypothesis(complexity_mod1,"moGeneration > moGeneration:Condition2", class = "bsp"))
plot(hypothesis(complexity_mod1,"moGeneration > moGeneration:Condition3", class = "bsp")) 
plot(hypothesis(complexity_mod1,"moGeneration > moGeneration:Condition4", class = "bsp")) 
plot(hypothesis(complexity_mod1,"moGeneration:Condition2 = moGeneration:Condition3", class = "bsp"))
plot(hypothesis(complexity_mod1,"moGeneration:Condition2 = moGeneration:Condition4", class = "bsp"))
plot(hypothesis(complexity_mod1,"moGeneration:Condition3 = moGeneration:Condition4", class = "bsp"))


# Plot conditional effects
conditional_effects(complexity_mod1)

conditional_effects(complexity_mod1, effects = "Generation", conditions = make_conditions(complexity_mod1, vars = "Condition"))
```


