---
title: "Model 2: conventionality"
author: "Sophia Kleist Karlson"
date: "20 nov 2020"
output: html_document
---

Model 2: conventionality

```{r}
save.image(file='yoursession.RData')
#To load this data later you can use:
load('yoursession.RData')
```

```{r}
# set working directory
setwd("~/Social Transmission Study/Analysis of drawings/")

# load necessary packages through pacman
pacman::p_load(tidyverse, brms, ggplot2, stringr, dplyr, bayesplot)

# RStudio version
RStudio.Version()

# read data and delete the first unnecessary column
data_conv <- read_csv("data/csv_files/all_data_w_all_conv_source.csv") #we use all_data_w_all_conv_source.csv
data_conv$X1 <- NULL
```


Preparing the data and checking stuff
```{r}
# Checking classes

# Generation, complexity, conventionality and confidence should be numeric
class(data_conv$Generation)
class(data_conv$Confidence)
class(data_conv$Conventionality)

# Subject and Drawing ID should be character
class(data_conv$Subject)
class(data_conv$Drawing_ID)

# Chain, condition and Source_image should be factors
class(data_conv$Chain)
class(data_conv$Condition)
class(data_conv$Source_image)

data_conv$Chain <- as.factor(data_conv$Chain)
data_conv$Condition <- as.factor(data_conv$Condition)
data_conv$Source_image <- as.factor(data_conv$Source_image)


# Chose the variables needed for the model
df_conventionality <- data_conv %>% select(Subject, Chain, Generation, Condition, Source_image, Conventionality)

# Z-score outcome variable to make it easier to deal with and interpret
df_conventionality$Conventionality <- scale(df_conventionality$Conventionality)


# check mean complexity of each of the conditions
Cond1_conv <- df_complexity %>% subset(Condition == 1) %>% subset(Generation == 0) %>% select(Complexity) 
Cond1_conv$Complexity <- as.numeric(Cond1_conv$Complexity)
mean(Cond1_conv$Complexity) # at gen 0: 0.759147. Overall: 0.8644237

Cond2_conv <- df_complexity %>% subset(Condition == 2) %>% subset(Generation == 0) %>% select(Complexity) 
Cond2_conv$Complexity <- as.numeric(Cond2_conv$Complexity)
mean(Cond2_conv$Complexity) # at gen 0: 0.7259283. Overall: -0.3349807

Cond3_conv <- df_complexity %>% subset(Condition == 3) %>% subset(Generation == 0) %>% select(Complexity)
Cond3_conv$Complexity <- as.numeric(Cond3_conv$Complexity)
mean(Cond3_conv$Complexity) # at gen 0: 0.7027229. Overall: -0.2500194

Cond4_conv <- df_complexity %>% subset(Condition == 4) %>% subset(Generation == 0) %>% select(Complexity)
Cond4_conv$Complexity <- as.numeric(Cond4_conv$Complexity)
mean(Cond4_conv$Complexity) # at gen 0: 0.7707145. Overall: -0.2794236
```


Modeling
```{r}
# Set seed so that the analysis can be re-run and give the same results
set.seed(555)


# Define the model - bf is short for brmsformula
convention_mod <- bf(Conventionality ~ 0 + Condition + mo(Generation) + Condition:mo(Generation) + 
                       (1 + Condition | gr(Subject, by = Chain)) +
                       (1 + Condition + mo(Generation) + Condition:mo(Generation) | Source_image))

# Figure out what priors we'll need
get_prior(convention_mod, family = gaussian, df_conventionality)

# Checking range, mean and standard deviation of complexity, to determine which family to choose and to use for beta-prior
range(df_conventionality$Conventionality)
mean(df_conventionality$Conventionality)
sd(df_conventionality$Conventionality)


# For choosing the sd prior
df_subj <- df_conventionality %>% group_by(Subject) %>% summarize(conv_mean = mean(Conventionality)) # find mean conventionality for each participant
sd(df_subj$conv_mean)#get the standard deviation of the mean conventionality for each participant (0.2970962). Divide this in two (0.1485481) # scaled = 0.11, half = 0.06

# do the same, but grouping by source image
df_source <- df_conventionality %>% group_by(Source_image) %>% summarize(conv_mean = mean(Conventionality)) # find mean conventionality for each source image
sd(df_source$conv_mean)# 0.3502272, half of this = 0.1751136 # scaled = 0.12, half = 0.06


# setting priors
prior_convention_mod <- c(
  prior(normal(0, 1),           class = b), #mean and sd of Conventionality # 4.33, 2.80
  prior(normal(1, 0.5),         class = sigma), #mean: sd of Conventionality. sigma: half of the sd of Conventionality # 2.80, 1.40
  prior(normal(0, 0.06),        class = sd), #mean: 0 (I expect that they might not vary at all). sd for the mean conv for each source image = 0.35. sigma should go from 0 (the mean of the prior) to around that -> sigma: 0.18.
  #prior(normal(0, 0.15),        class = sd), #mean: 0 (I expect that they might not vary at all). sd for the mean conv for each subject = 0.30. sigma should go from 0 (the mean of the prior) to around that -> sigma: 0.15.
  prior(lkj(1),                 class = cor), # I choose lkj prior of 1
  
  # simo priors for the monotonic generation variable: mean is 1 for a uniform prior, sigma is K-1, where K is the number of levels in the monotonic variable (we have 8 generations)
  prior(dirichlet(rep(1, 7)),   class = simo, coef = moGeneration:Condition21),                 
  prior(dirichlet(rep(1, 7)),   class = simo, coef = moGeneration:Condition31),             
  prior(dirichlet(rep(1, 7)),   class = simo, coef = moGeneration:Condition41),            
  prior(dirichlet(rep(1, 7)),   class = simo,  coef = moGeneration1)
  
  #prior(normal(4.33, 2.80),     class = Intercept) #mean and sd of Conventionality
)


# Running the model to check priors
convention_mod0 <- brm(
  formula = convention_mod, 
  prior = prior_convention_mod,
  data = df_conventionality,
  chains = 2,
  cores = 2,
  sample_prior = "only"
)


# Prior predictive check
pp_check(convention_mod0, nsamples = 100) 


# The actual model:
convention_mod1 <- brm(
  formula = convention_mod, 
  prior = prior_convention_mod,
  data = df_conventionality,
  chains = 2,
  cores = 2,
  sample_prior = T,
  iter = 4000,
  control = list(adapt_delta=0.99, max_treedepth=20)
)

# Posterior predictive check
pp_check(convention_mod1, nsamples = 100)



# Model summary
summary(convention_mod1) # Warnings? Suspicious Rhat activity? Bad priors?


# Plot conditional effects
conditional_effects(convention_mod1)
conditional_effects(convention_mod1, effects = "Condition", conditions = make_conditions(convention_mod1, vars = "Generation"))

conditional_effects(convention_mod1, effects = "Generation", conditions = make_conditions(convention_mod1, vars = "Condition"))


# Trace plots
plot(convention_mod1)


# Rank trace plots
mcmc_rank_overlay(convention_mod1, 
                  pars = c("b_Condition1", "b_Condition2", "b_Condition3", "b_Condition4")) + 
  theme_classic()

mcmc_rank_overlay(convention_mod1, 
                  pars = c("bsp_moGeneration", "bsp_moGeneration:Condition2", "bsp_moGeneration:Condition3", "bsp_moGeneration:Condition4")) + 
  theme_classic()

mcmc_rank_overlay(convention_mod1, 
                  pars = c("sigma")) + 
  theme_classic()



# After trying different hypotheses, these turned out to be the ones with highest evidence ratio

# average effects of conditions
hypothesis(convention_mod1,"(Condition1*8 + 0.01*28)/8 = 0")
hypothesis(convention_mod1,"(Condition2*8 + 0.03*28)/8 = 0")
hypothesis(convention_mod1,"(Condition3*8 + 0.05*28)/8 = 0")
hypothesis(convention_mod1,"(Condition4*8 + 0.02*28)/8 < 0")

# these two could have replaced the two top ones, but they gave slightly smaller estimated error, so I chose the other option as seen above
#hypothesis(convention_mod1,"(0.82*8 + moGeneration*28)/8 > 0", class="bsp")
#hypothesis(convention_mod1,"(0.67*8 + moGeneration:Condition2*28)/8 < 0", class="bsp")
#hypothesis(convention_mod1,"(0.65*8 + moGeneration:Condition3*28)/8 < 0", class="bsp")
#hypothesis(convention_mod1,"(0.62*8 + moGeneration:Condition4*28)/8 = 0", class="bsp")

# relations between the conditions
hypothesis(convention_mod1,"(Condition1*8 + 0.01*28)/8 = (Condition2*8 + 0.03*28)/8") 
hypothesis(convention_mod1,"(Condition1*8 + 0.01*28)/8 < (Condition3*8 + 0.05*28)/8")
hypothesis(convention_mod1,"(Condition1*8 + 0.01*28)/8 > (Condition4*8 + 0.02*28)/8")
hypothesis(convention_mod1,"(Condition2*8 + 0.03*28)/8 < (Condition3*8 + 0.05*28)/8")
hypothesis(convention_mod1,"(Condition2*8 + 0.03*28)/8 > (Condition4*8 + 0.02*28)/8")
hypothesis(convention_mod1,"(Condition3*8 + 0.05*28)/8 > (Condition4*8 + 0.02*28)/8")


# overall effect of generation
hypothesis(convention_mod1,"((moGeneration + moGeneration:Condition2 + moGeneration:Condition3 + moGeneration:Condition4)/4) > 0", class = "bsp")

# effects of the interactions between generation and conditions
hypothesis(convention_mod1,"moGeneration = 0", class = "bsp")
hypothesis(convention_mod1,"moGeneration:Condition2 > 0", class = "bsp") 
hypothesis(convention_mod1,"moGeneration:Condition3 > 0", class = "bsp") 
hypothesis(convention_mod1,"moGeneration:Condition4 = 0", class = "bsp")

hypothesis(convention_mod1,"moGeneration = moGeneration:Condition2", class = "bsp")
hypothesis(convention_mod1,"moGeneration < moGeneration:Condition3", class = "bsp") 
hypothesis(convention_mod1,"moGeneration = moGeneration:Condition4", class = "bsp") 
hypothesis(convention_mod1,"moGeneration:Condition2 = moGeneration:Condition3", class = "bsp")
hypothesis(convention_mod1,"moGeneration:Condition2 = moGeneration:Condition4", class = "bsp")
hypothesis(convention_mod1,"moGeneration:Condition3 > moGeneration:Condition4", class = "bsp") 

# is average slope of the three memory conditions higher than that of copy?
hypothesis(convention_mod1,"moGeneration < (moGeneration:Condition2 + moGeneration:Condition3 +moGeneration:Condition4)/3", class = "bsp") # no, there is more evidence that they are equal:
#Hypothesis Estimate Est.Error CI.Lower CI.Upper Evid.Ratio Post.Prob Star
#1 (moGeneration)-((... = 0    -0.02      0.02    -0.06     0.01      31.56      0.97  

#Hypothesis Estimate Est.Error CI.Lower CI.Upper Evid.Ratio Post.Prob Star
#1 (moGeneration)-((... < 0    -0.02      0.02    -0.05     0.01       8.01      0.89 

# initial hyps that did not have the highest ER
hypothesis(convention_mod1,"(Condition1*8 + 0.01*28)/8 < (Condition2*8 - 0.03*28)/8") 
hypothesis(convention_mod1,"(Condition1*8 + 0.01*28)/8 < (Condition4*8 - 0.21*28)/8")
hypothesis(convention_mod1,"(Condition2*8 - 0.03*28)/8 < (Condition4*8 - 0.21*28)/8")
hypothesis(convention_mod1,"(Condition3*8 - 0.05*28)/8 < (Condition4*8 - 0.21*28)/8")

hypothesis(convention_mod1,"moGeneration:Condition4 > 0", class = "bsp")

hypothesis(convention_mod1,"moGeneration < moGeneration:Condition2", class = "bsp") 
hypothesis(convention_mod1,"moGeneration < moGeneration:Condition4", class = "bsp") 
hypothesis(convention_mod1,"moGeneration:Condition2 < moGeneration:Condition3", class = "bsp")
hypothesis(convention_mod1,"moGeneration:Condition2 < moGeneration:Condition4", class = "bsp")
hypothesis(convention_mod1,"moGeneration:Condition3 < moGeneration:Condition4", class = "bsp")



# plot the best hypotheses
plot(hypothesis(convention_mod1,"(Condition1*8 + 0.01*28)/8 = 0"))
plot(hypothesis(convention_mod1,"(Condition2*8 + 0.03*28)/8 = 0"))
plot(hypothesis(convention_mod1,"(Condition3*8 + 0.05*28)/8 = 0"))
plot(hypothesis(convention_mod1,"(Condition4*8 + 0.02*28)/8 < 0"))

# relations between the conditions
plot(hypothesis(convention_mod1,"(Condition1*8 + 0.01*28)/8 = (Condition2*8 + 0.03*28)/8"))
plot(hypothesis(convention_mod1,"(Condition1*8 + 0.01*28)/8 < (Condition3*8 + 0.05*28)/8"))
plot(hypothesis(convention_mod1,"(Condition1*8 + 0.01*28)/8 > (Condition4*8 + 0.02*28)/8"))
plot(hypothesis(convention_mod1,"(Condition2*8 + 0.03*28)/8 < (Condition3*8 + 0.05*28)/8"))
plot(hypothesis(convention_mod1,"(Condition3*8 + 0.05*28)/8 > (Condition4*8 + 0.02*28)/8"))
plot(hypothesis(convention_mod1,"(Condition2*8 + 0.03*28)/8 > (Condition4*8 + 0.02*28)/8"))


# overall effect of generation
plot(hypothesis(convention_mod1,"((moGeneration + moGeneration:Condition2 + moGeneration:Condition3 + moGeneration:Condition4)/4) > 0", class = "bsp"))

# effects of the interactions between generation and conditions
plot(hypothesis(convention_mod1,"moGeneration = 0", class = "bsp"))
plot(hypothesis(convention_mod1,"moGeneration:Condition2 > 0", class = "bsp")) 
plot(hypothesis(convention_mod1,"moGeneration:Condition3 > 0", class = "bsp")) 
plot(hypothesis(convention_mod1,"moGeneration:Condition4 = 0", class = "bsp"))

plot(hypothesis(convention_mod1,"moGeneration = moGeneration:Condition2", class = "bsp"))
plot(hypothesis(convention_mod1,"moGeneration < moGeneration:Condition3", class = "bsp")) 
plot(hypothesis(convention_mod1,"moGeneration = moGeneration:Condition4", class = "bsp")) 
plot(hypothesis(convention_mod1,"moGeneration:Condition2 = moGeneration:Condition3", class = "bsp"))
plot(hypothesis(convention_mod1,"moGeneration:Condition2 = moGeneration:Condition4", class = "bsp"))
plot(hypothesis(convention_mod1,"moGeneration:Condition3 > moGeneration:Condition4", class = "bsp"))


class(convention_mod1) # "brmsfit"
```
